const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94703266143"
const SESSION_ID = "PRABATH-MD~9z1yyKCI#QZm1dYB7xuXugIcHSBBe7it2px8VbmzFTJ_lbIrBuh8"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
